extends: 
  - eslint:recommended

env:
  commonjs: true
  es2021: true
  node: true

parserOptions:
  ecmaVersion: 12
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0 # FIXME: remove when rule will be adjusted for new nodejs version
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  complexity: ["error", { "max" : 7 }]
  max-depth: ["error", { "max" : 2 }]
  max-nested-callbacks: ["error", { "max" : 2 }]
  max-params: ["error", { "max" : 4 }]
  max-statements: ["error", { "max" : 15 }, { "ignoreTopLevelFunctions": false }]
  max-len: ["error", {"code" : 120, "ignoreUrls": true}]
  max-lines: ["error", { "max": 250, "skipComments": true, "skipBlankLines": true }]
  no-multiple-empty-lines: ["error", { "max": 1 }]
  space-before-function-paren: ["error", { "anonymous": "always", "named": "never", "asyncArrow": "always" }]